/**
 * Copyright 2015-2016, Google, Inc.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';

const path = require('path');
const url = require('url');
const config = require('../config/config');

const libImages = require('../lib/images');
const dataFetcher = require('../lib/data-fetcher');
const libLighthouse = require('../lib/lighthouse');
const libManifest = require('../lib/manifest');

const Pwa = require('../models/pwa');
const cache = require('../lib/data-cache');

const db = require('../lib/model-' + config.get('DATA_BACKEND'));
const gcloud = require('google-cloud');
const ds = gcloud.datastore({
  projectId: config.get('GCLOUD_PROJECT')
});

const DEFAULT_SORT_TYPE_KEY = 'score';
const ENTITY_NAME = 'PWA';
const E_MANIFEST_INVALID_URL = exports.E_MANIFEST_INVALID_URL = 2;
const E_MANIFEST_URL_MISSING = exports.E_MANIFEST_URL_MISSING = 3;
const E_MISING_USER_INFORMATION = exports.E_MISING_USER_INFORMATION = 4;
const E_NOT_A_PWA = exports.E_NOT_A_PWA = 5;
const LIST_ENTITY_NAME = 'PWA_LIST';
const CACHE_TIMEOUT = 60;

const SORT_TYPE_MAP = new Map([
  ['name', {name: 'name', field: 'manifest.name'}],
  ['newest', {name: 'newest', field: 'created', config: {descending: true}}],
  ['score', {name: 'score', field: 'lighthouseScore', config: {descending: true}}]
]);

/**
 * List of PWAs.
 *
 * @param {number} skip specifies the starting point for handling pagination
 * @param {number} limit number of results to return
 * @param {string} sort the field name to sort the results
 * @return {Pwa} the PWA from DB
 */
exports.list = function(skip, limit, sort) {
  let sortType = SORT_TYPE_MAP.get(DEFAULT_SORT_TYPE_KEY);
  if (sort) {
    sortType = SORT_TYPE_MAP.get(sort) || sortType;
  }

  const cacheKey = JSON.stringify({
    kind: LIST_ENTITY_NAME,
    skip: skip,
    limit: limit,
    sort: sortType.name
  });

  return cache.get(cacheKey)
    .then(result => {
      const pwas = result.pwas.map(pwa => {
        return Object.assign(new Pwa(), pwa);
      });

      return {
        pwas: pwas,
        hasMore: result.hasMore
      };
    })
    .catch(_ => {
      return db.list(ENTITY_NAME, skip, limit, sortType)
        .then(result => {
          const pwas = result.entities.map(pwa => {
            return Object.assign(new Pwa(), pwa);
          });

          const resultPage = {
            pwas: pwas,
            hasMore: result.hasMore
          };

          cache.set(cacheKey, resultPage, CACHE_TIMEOUT);
          return resultPage;
        });
    });
};

/**
 * Finds a PWA by key.
 *
 * @param {number} key of the PWA
 * @return {Pwa} the PWA from DB
 */
exports.find = function(key) {
  const cacheKey = JSON.stringify({kind: ENTITY_NAME, key: key});
  return cache.get(cacheKey)
    .then(pwa => {
      return Object.assign(new Pwa(), pwa);
    })
    .catch(_ => {
      return db.read(ENTITY_NAME, key)
        .then(pwa => {
          const pwaInstance = Object.assign(new Pwa(), pwa);
          cache.set(cacheKey, pwaInstance, CACHE_TIMEOUT);
          return pwaInstance;
        });
    });
};

/**
 * Finds a PWA by its manifest URL from DB.
 *
 * @param {string} manifestUrl of the PWA's manifest
 * @return {Pwa} the PWA from DB
 */
exports.findByManifestUrl = function(manifestUrl) {
  return new Promise((resolve, reject) => {
    const query = ds.createQuery(ENTITY_NAME).filter('manifestUrl', manifestUrl);
    ds.runQuery(query, (err, pwas) => {
      if (err) {
        return reject(err);
      }

      if (pwas.length === 0) {
        return resolve(null);
      }

      pwas[0].data.id = pwas[0].key.id;
      var pwa = Object.assign(new Pwa(), pwas[0].data);
      return resolve(pwa);
    });
  });
};

/**
 * Saves a PWA to the DB.
 *
 * Steps:
 *  1) Fetches the manifest.
 *  2) Fetches the description from the metadata if needed.
 *  3) Saves the PWA to get the autogenerated id.
 *  4) Updates the main Icon of the PWA.
 *  5) Fetches and saves the Lighthouse info.
 *  6) Updates the lighthouseScore of the PWA.
 *
 * @param {Pwa} pwa to update
 * @param {Manifest} manifest that contains the icon url to fetch
 * @return {Pwa} the updated PWA
 */
exports.save = function(pwa) {
  if (!pwa) {
    return Promise.reject('pwa is null');
  }

  if (!(pwa instanceof Pwa)) {
    return Promise.reject(E_NOT_A_PWA);
  }

  if (!pwa.manifestUrl) {
    return Promise.reject(E_MANIFEST_URL_MISSING);
  }

  if (!(url.format(pwa.manifestUrl).startsWith('http://') ||
        url.format(pwa.manifestUrl).startsWith('https://'))) {
    return Promise.reject(E_MANIFEST_INVALID_URL);
  }

  if (!pwa.user || !pwa.user.id) {
    return Promise.reject(E_MISING_USER_INFORMATION);
  }

  return this._save(pwa);
};

// Internal only; we only export so that we can monkey patch in tests…
exports._save = function(pwa) {
  return this.findByManifestUrl(pwa.manifestUrl)
    .then(existingPwa => {
      pwa = existingPwa || pwa;
      pwa.updated = new Date();
      return libManifest.fetchManifest(pwa.manifestUrl);
    })
    .then(manifest => {
      pwa.manifest = manifest;
      return this.fetchMetadataDescription(pwa);
    })
    .then(description => {
      pwa.metaDescription = description;
      return db.update(ENTITY_NAME, pwa.id, pwa);
    })
    .then(savedPwa => {
      this.updateIcon(savedPwa, pwa.manifest)
        .then(savedPwa => {
          this.updateLighthouseInfo(savedPwa);
        });
      return savedPwa;
    });
};

/**
 * Deletes a PWA from DB.
 *
 * @param {number} key of the PWA
 * @return {Promise<>}
 */
exports.delete = function(key) {
  return db.delete(ENTITY_NAME, key);
};

/**
 * Updates the description from the webpage's metadata if not present in the Manifest.
 *
 * @param {Pwa} pwa to update
 * @return {Promise<string>} with the description or error
 */
exports.fetchMetadataDescription = function(pwa) {
  return new Promise((resolve, reject) => {
    if (!pwa.description && pwa.absoluteStartUrl) {
      dataFetcher.fetchMetadataDescription(pwa.absoluteStartUrl)
        .then(description => {
          resolve(description);
        })
        .catch(err => {
          console.log(err);
          resolve(null);
        });
    } else {
      resolve(null);
    }
  });
};

/**
 * Updates the main icon of a PWA.
 *
 * @param {Pwa} pwa to update
 * @param {Manifest} manifest that contains the icon url to fetch
 * @return {Pwa} the updated PWA
 */
exports.updateIcon = function(pwa, manifest) {
  return new Promise((resolve, reject) => {
    const bestIconUrl = manifest.getBestIconUrl();
    const extension = path.extname(url.parse(bestIconUrl).pathname);
    const bucketFileName = pwa.id + extension;

    libImages.fetchAndSave(bestIconUrl, bucketFileName)
      .then(savedUrl => {
        pwa.iconUrl = savedUrl;
        var updatedPwa = db.update(ENTITY_NAME, pwa.id, pwa);
        console.log('Updated PWA Image: ', pwa.id);
        resolve(updatedPwa);
      })
      .catch(err => {
        console.log(err);
        resolve(null);
      });
  });
};

/**
 * Updates the Lighthouse information and sets the lighthouseScore for a PWA.
 *
 * @param {Pwa} pwa to get and update the lighthouse info.
 * @return {Pwa} the updated PWA
 */
exports.updateLighthouseInfo = function(pwa) {
  return new Promise((resolve, reject) => {
    libLighthouse.fetchAndSave(pwa.id)
    .then(lighthouse => {
      pwa.lighthouseScore = lighthouse.lighthouseInfo.totalScore;
      var updatedPwa = db.update(ENTITY_NAME, pwa.id, pwa);
      console.log('Updated PWA Lighthouse info for: ', pwa.id);
      resolve(updatedPwa);
    })
    .catch(err => {
      console.log(err);
      resolve(null);
    });
  });
};
